look for ../../../data/ instead of ../../data/
Fix issue 394:
src/hamster-service &
...
FileNotFoundError: [Errno 2] No such file or directory
when there is no hamster.db.