fix xml export
setAttribute expects strings, otherwise
  File "/usr/lib64/python3.6/xml/dom/minidom.py", line 305, in _write_data
    data = data.replace("&", "&amp;").replace("<", "&lt;"). \
TypeError: an integer is required (got type str)